export { default as Home } from './home'
export { default as SignIn } from './sign-in'
export { default as Game } from './game'
export { default as Profile } from './profile'
export { default as Play } from './play'
export { default as NotFound } from './not-found'
export { default as Leaderboard } from './leaderboard'
